---
title: "Party Panel 19.1-pre1 Report"
author: "Lizet Wilkens, Judith Noijen & Gjalt-Jorn Peters"
date: "`r format(Sys.time(), '%d %b %Y at %H:%M:%S');`"
output:
  html_document:
    toc: true
    #toc_float: true
    toc_depth: 5
    theme: united
    #css: "B:\\Data\\research\\party panel\\partypanel-shared\\party-panel-reports.css"
editor_options: 
  chunk_output_type: console
---

Introduction
------------

Party Panel is a Dutch panel study where determinants and beliefs underlying health behaviors in the Dutch nightlife are mapped. The fifth wave started on [[[ADD]]] 2019 and explored behavior related to sleeping hygiene.

This document is the report of the first pre-study, where ... 

```{r echo=FALSE, warning=FALSE, message=FALSE }

### General purpose utilies and installing missing packages when requiring
if (!'ufs' %in% row.names(installed.packages()))
  devtools::install_gitlab('r-packages/ufs',
                           quietly = TRUE,
                           dependencies = FALSE);

### File input/output
ufs::safeRequire('here');

### Working with decision trees
ufs::safeRequire('data.tree');
ufs::safeRequire('DiagrammeR');

### General purpose utilities, dataviz, etc
require('ufs');

### Get dev versions of some packages
devtools::install_gitlab("r-packages/yum",
                         quietly = TRUE,
                         dependencies = FALSE);
devtools::install_gitlab("r-packages/justifier",
                         quietly = TRUE,
                         dependencies = FALSE);

### Set basic configuration variables
if (!exists('ppWave')) ppWave <- '19.1';
if (!exists('ppReport')) ppReport <- 'pre1';

### Set paths
if (!exists('basePath')) basePath <- here::here();
justificationsPath <-
  here::here('preparation',
             ppReport);
workingPath <-
  file.path(justificationsPath,
            "results--intermediate");

```

```{r import-jmd-files}

justifications <-
  justifier::load_justifications(file.path(justificationsPath,
                                 "pp19.1-target-behavior-selection.jmd"));

```

```{r save-decision-trees}

for (i in names(justifications$decisionGraphs)) {
  DiagrammeR::export_graph(justifications$decisionGraphs[[i]],
                           file_name = file.path(workingPath,
                                                 paste0(i, ".pdf")));
}

```

