
### Get a list of stored workspaces
workspaces <- list.files(here::here('workspaces'),
                         pattern='^autogenerated--.*\\.RData',
                         full.names=TRUE);

### Get most recent one
if (length(workspaces) > 0) {
  lastWorkspace <- tail(sort(workspaces), 1);
  load(lastWorkspace);
  rm(lastWorkspace);
} else {
  stop("No automatically stored workspaces available!");
}

rm(workspaces);
