########################################################################
### Settings for this wave
########################################################################
waveNumber <- "19.1";
surveyId <- 622298;
startDate <- '2019-07-04';
categoricalQuestions <- c('informedConsent', 'gender',
                          'hasJob',
                          'currentEducation', 'prevEducation',
                          'country');
behaviors <- c('pre', 'post');

options(ufs.debug = FALSE);

########################################################################
### Derivations and packages
########################################################################
require('rmarkdown');

if (require('here') && (!exists('rootPath') || is.null(rootPath))) {
  basePath <- here::here();
  rootPath <- file.path(basePath, "..");
} else {
  rootPath <- "B:/Data/research/party panel";
  basePath <- file.path(rootPath, paste0("partypanel-", waveNumber));
}
sharedPath <- file.path(rootPath, "partypanel-shared");
outputPath <- file.path(basePath, 'results - reports');
scriptPath <- file.path(basePath, 'results - analysis scripts');
workspacePath <- file.path(basePath, 'workspaces');

reportLoginStringFilePath <-
  file.path(sharedPath, 'report-upload-login-string.txt')
resultsLoginStringFilePath <-
  file.path(sharedPath, 'results-upload-login-string.txt')

########################################################################
### Rendering command
########################################################################

render(input=file.path(sharedPath, 'party-panel-report.Rmd'),
       output_file=file.path(outputPath, paste('party panel',
                                               waveNumber,
                                               'report.html')),
       params=list(waveNumber=waveNumber,
                   basePath=basePath,
                   sharedPath=sharedPath,
                   surveyId=surveyId,
                   startDate=startDate,
                   behaviors=behaviors,
                   categoricalQuestions=categoricalQuestions),
       encoding="UTF-8");

### Save dataframe for potential later use.
assign(paste0("dat.pp", waveNumber), dat);
if (exists('ppDataframes')) {
  ppDataframes[length(ppDataframes) + 1] <- paste0("dat.pp", waveNumber);
}

### Save recruitment information for potential later use.
assign(paste0("ppRecrInfo.", waveNumber), recruitmentInfo);
if (exists('ppRecrInfo')) {
  ppRecrInfo[length(ppRecrInfo) + 1] <- paste0("ppRecrInfo.", waveNumber);
}

### Save the five section markers for visualisation of dropout rates over all waves
assign(paste0("ppFiveSectionMarkers.", waveNumber), fiveSectionMarkers);

### Store workspace; first delete most old automatically saved
### workspaces
if (dir.exists(workspacePath)) {
  oldfiles <- list.files(workspacePath,
                         pattern='^autogenerated--.*\\.RData',
                         full.names=TRUE);

  ### Delete all but most recent one
  if (length(oldfiles) > 1) {
    unlink(head(sort(oldfiles), -1));
  }

  ### Housecleaning
  rm(oldfiles);

  ### Store new workspace
  workspaceDate <- Sys.time();
  workspaceFilename <-
    format(workspaceDate,
           "autogenerated--%Y-%m-%d--%H-%M--after-report-scripts.RData");
  tryCatch({
    save.image(file=file.path(workspacePath,
                              workspaceFilename));
  }, error = function(e) {
    warning(paste0("Encountered error when trying to save workspace to ",
                   workspaceFilename, "!\n"));
  });

}

########################################################################
### Uploading report to secure site
########################################################################

uploadPassword <- readLines(reportLoginStringFilePath);

if (require('RCurl')) {
  if (url.exists('partypanel.nl')) {
    ftpUpload(file.path(rootPath,
                        paste0("partypanel-", waveNumber),
                        "results - reports",
                        paste0("party panel ", waveNumber, " report.html")),
              paste0("ftp://partypanel.nl/", waveNumber, "/index.html"),
              userpwd=uploadPassword)
    cat("Uploaded report for wave ", waveNumber, " to the secured site using FTP.\n", sep="");
  }
}

########################################################################
### Uploading report for publication (only uncomment after embargo)
########################################################################

uploadPassword <- readLines(resultsLoginStringFilePath);

if (require('RCurl')) {
  if (url.exists('partypanel.nl')) {
    ftpUpload(file.path(rootPath,
                        paste0("partypanel-", waveNumber),
                        "results - reports",
                        paste0("party panel ", waveNumber, " report.html")),
              paste0("ftp://partypanel.nl/", waveNumber, "/report.html"),
              userpwd=uploadPassword)
    cat("Uploaded report for wave ", waveNumber, " to the public site using FTP.\n", sep="");
  }
}
