---
output: html_document
editor_options: 
  chunk_output_type: console
---

#### Infographic

##### Sleeping behavior

```{r infographic-sleeping-behavior-categorization}

sleepHours_toCategory <- function(x) {
  return(
    factor(
      ifelse(is.na(x),
             NA,
             ifelse(x < 3,
                    1,
                    ifelse(x < 6,
                           2,
                           ifelse(x < 8,
                                  3,
                                  4)))),
      levels=1:4,
      labels=c("Minder dan 3 uur",
               "4-5 uur",
               "6-7 uur",
               "8 uur of meer"))
  );
}

dat$weekdaySleep_cat <-
  sleepHours_toCategory(dat$weekdaySleep);

dat$goingOutSleep_cat <-
  sleepHours_toCategory(dat$goingOutSleep);

dat$atFestivalSleep_other_cat <-
  sleepHours_toCategory(dat$atFestivalSleep_other);

dat$afterFestivalSleep_other_cat <-
  sleepHours_toCategory(dat$afterFestivalSleep_other);

```

###### Hours of sleep on a weekday:

```{r infographic-sleeping-behavior-1}
pander::pander(rosetta::freq(dat$weekdaySleep_cat));
```

###### Hours of sleep when going out:

```{r infographic-sleeping-behavior-2}
pander::pander(rosetta::freq(dat$goingOutSleep_cat));
```

###### Hours of sleep at a multi-day festival:

```{r infographic-sleeping-behavior-3}
pander::pander(rosetta::freq(dat$atFestivalSleep_other_cat));
```

###### Hours of sleep on after a one-day festival:

```{r infographic-sleeping-behavior-4}
pander::pander(rosetta::freq(dat$afterFestivalSleep_other_cat));
```

##### Animation

###### How often do participant make sure they sleep enough?

```{r animation-sleeping-hygiene-1}

enforceSleepPattern_to_cat <- function(x) {
  return(
    factor(
      ifelse(is.na(x),
             NA,
             ifelse(x < 3,
                    1,
                    ifelse(x == 3,
                           2,
                           3))),
      levels=1:3,
      labels=c("Soms",
               "Wel eens",
               "Vaak"))
  );
}

dat$sleepBehav_pre_cat <-
  enforceSleepPattern_to_cat(dat$sleepBehav_pre);
dat$sleepBehav_post_cat <-
  enforceSleepPattern_to_cat(dat$sleepBehav_post);

```
Scale from '(almost) never', 'sometimes', 'regularly', 'often', '(almost) always'.

####### 3 nights before going out

```{r infographic-sleep-behavior-1}

pander::pander(rosetta::freq(dat$sleepBehav_pre_cat));

```

####### 3 nights after going out

```{r infographic-sleep-behavior-2}

pander::pander(rosetta::freq(dat$sleepBehav_post_cat));

```


